package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type AutoGenerated struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Image       string  `json:"image"`
	Rating      struct {
		Rate  float64 `json:"rate"`
		Count int     `json:"count"`
	} `json:"rating"`
}

func main() {
	apiUrl := "https://fakestoreapi.com/products"
	response, err := http.Get(apiUrl)
	if err != nil {
		fmt.Println("request error:", err)
		return
	}
	defer response.Body.Close()

	body, err := io.ReadAll(response.Body)
	if err != nil {
		fmt.Println("response error:", err)
		return
	}

	var data []AutoGenerated

	err = json.Unmarshal(body, &data)
	if err != nil {
		fmt.Println("Gagal mengurai JSON:", err)
		return
	}
	for _, val := range data {
		fmt.Println("=================")
		fmt.Println("Title:", val.Title)
		fmt.Println("Price:", val.Price)
		fmt.Println("Category:", val.Category)
		fmt.Println("=================")
	}
}
